version: '3.1'

services:
  app:
    build: .
    command: /home/leaf3/run.sh
    depends_on:
      - graph-db
      - sql-db
    deploy:
      replicas: 2
    env_file: env/prod/leaf3.env
    restart: always
    user: leaf3:leaf3
    volumes:
      - static_files:/home/leaf3/static
      - type: bind
        source: ./env/prod/leaf3.environ
        target: /home/leaf3/conf/.environ

  graph-db:
    env_file: env/prod/neo4j.env
    image: neo4j:latest
    ports:
        - 7474:7474
        - 7687:7687
    restart: always
    volumes:
      - ~/leaf3/volumes/graph-db:/data

  lb:
    build: nginx
    depends_on:
      - app
    ports:
      - 80:8080
    restart: always
    volumes:
      - static_files:/home/leaf3/static

  sql-db:
    command: --default-authentication-plugin=mysql_native_password
    env_file: env/prod/neo4j.env
    image: mysql
    ports:
        - 3306:3306
    restart: always
    volumes:
      - ~/leaf3/volumes/sql-db:/var/lib/mysql

volumes:
  static_files:
