# Generated by Django 4.0.1 on 2022-01-19 23:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

  initial = True

  dependencies = [
      migrations.swappable_dependency(settings.AUTH_USER_MODEL),
  ]

  operations = [
      migrations.CreateModel(
          name='Tree',
          fields=[
              ('id',
               models.BigAutoField(auto_created=True,
                                   primary_key=True,
                                   serialize=False,
                                   verbose_name='ID')),
              ('created', models.DateTimeField(auto_now_add=True)),
              ('updated', models.DateTimeField(auto_now=True)),
              ('description',
               models.TextField(max_length=100, blank=True, null=True)),
              ('name', models.CharField(max_length=50)),
              ('creator',
               models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                 to=settings.AUTH_USER_MODEL)),
          ],
          options={
              'verbose_name': 'Tree',
              'verbose_name_plural': 'Trees',
              'db_table': 'trees',
          },
      ),
  ]
