# Generated by Django 4.0.1 on 2022-01-21 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

  dependencies = [
      ('tree', '0001_initial'),
  ]

  operations = [
      migrations.AddField(
          model_name='tree',
          name='uid',
          field=models.UUIDField(unique=True, default=1, blank=True,
                                 null=False),
          preserve_default=False,
      ),
  ]
