# Generated by Django 4.0.1 on 2022-01-21 20:34

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0002_tree_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tree',
            name='id',
        ),
        migrations.AlterField(
            model_name='tree',
            name='uid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=None, length=10, max_length=40, prefix='', primary_key=True, serialize=False),
        ),
    ]
