# Generated by Django 4.0.1 on 2022-01-21 20:37

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0003_remove_tree_id_alter_tree_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='uid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='23456789abcdefghijkmnopqrstuvwxyz', length=10, max_length=40, prefix='', primary_key=True, serialize=False),
        ),
    ]
